service: kezzle-clip-serving
frameworkVersion: "3"

provider:
    name: aws
    runtime: python3.11
    stage: dev
    region: ap-northeast-2
    ecr:
        images:
            koclip-image:
                path: ./ko_image_vectorizer
                platform: linux/amd64
            clip-image:
                path: ./image_vectorizer
                platform: linux/amd64
            koclip-keyword:
                path: ./ko_text_vectorizer
                platform: linux/amd64
            clip-keyword:
                path: ./text_vectorizer
                platform: linux/amd64

functions:
    image-vectorizer:
        architecture: x86_64
        image:
            name: clip-image
        timeout: 180
        memorySize: 1536
    ko-image-vectorizer:
        architecture: x86_64
        image:
            name: koclip-image
        timeout: 180
        memorySize: 1536
    keyword-vectorizer:
        architecture: x86_64
        image:
            name: clip-keyword
        events:
            - http:
                  path: /keyword
                  method: post
        timeout: 30
        memorySize: 1536
    ko-keyword-vectorizer:
        architecture: x86_64
        image:
            name: koclip-keyword
        events:
            - http:
                  path: /ko-keyword
                  method: post
        timeout: 30
        memorySize: 1536
